### ISSUE TITLE
Java map<_, char> not keeping value type as char when accessing

### ISSUE THREAD

**Issue by Dilan-s** [fuzz-d/dafny-bugs#6]
### Dafny version

4.0.0

### Code to produce this issue

```dafny
method Main() returns () {
  var v_map: map<bool, char> := map[true := 'c'];
  if true in v_map {
    var v_char: char := v_map[true];
    assert true;
  }
}
```

### Command to run and resulting output

```code
$ dafny /compile:4 /compileTarget:java test.dfy
Exception in thread "main" java.lang.ClassCastException: class java.lang.Character cannot be cast to class dafny.CodePoint (java.lang.Character is in module java.base of loader 'bootstrap'; dafny.CodePoint is in unnamed module of loader 'app')
        at _System.__default.Main(__default.java:16)
        at _System.__default.__Main(__default.java:20)
        at test.lambda$main$0(test.java:9)
        at dafny.Helpers.withHaltHandling(Helpers.java:327)
        at test.main(test.java:9)
```

### What happened?

Dafny verifies the program, but in Java throws an error (detailed above) which happens when accessing the value of a map (this occurs regardless of the type of the key) where the value is of type char. In all other languages (js, py, go, cs) this issue does not occur. This appears that the code generation for Java is casting the type of the value incorrectly.

### What type of operating system are you experiencing the problem on?

Linux

**Comment by fuzz-d** [comment]
There's also something weird going on here with equality:
```
method Main() {
	var v0 := 'q';
	var v3 := map[v0 := multiset{false}];
	print v3 == map['q' := multiset{false}];
}
```
outputs false for java (true in c#), but:
```
method Main() {
	var v3 := map['q' := multiset{false}];
	print v3 == map['q' := multiset{false}];
}
```
outputs true in all backends
